kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-namespace
spec:
  podSelector:
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            project: bookinfo-app
