
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: reverse-sso
spec:
  podSelector:
    matchLabels:
      app: reverse-sso
  ingress:
  - ports:
    - protocol: TCP
      port: 8080
