apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: httpd-mtls
  name: httpd-mtls
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd-mtls
  strategy: {}
  template:
    metadata:
      labels:
        app: httpd-mtls
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/ooichman-project/httpd-mtls
        name: httpd-mtls
        ports:
        - containerPort: 8443
        volumeMounts:
          - mountPath: "/opt/app-root/ssl"
            name: mtls-keys
            readOnly: true
          - name: ca-cert
            mountPath: /opt/app-root/CA/ca.crt
            subPath: ca.crt
        env:
        - name: SSL_CERT
          value: /opt/app-root/ssl/tls.crt
        - name: SSL_KEY
          value: /opt/app-root/ssl/tls.key
        - name: CA_CERT
          value: /opt/app-root/CA/ca.crt
        - name: ALLOWED_USER
          value: ooichman-redhat.com.example.local
      volumes:
        - name: mtls-keys
          secret:
            secretName: http-mtls-tls
        - name: ca-cert
          configMap:
            name: ca-cert